// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7Q-hf9nMb9QkigrxXV62oX_I4LgXpHrE',
    appId: '1:957697550017:web:c49fdc7fb312d7cc879640',
    messagingSenderId: '957697550017',
    projectId: 'bowlingpro-2bc7a',
    authDomain: 'bowlingpro-2bc7a.firebaseapp.com',
    storageBucket: 'bowlingpro-2bc7a.firebasestorage.app',
    measurementId: 'G-HHFX71JK0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYw028ZdxaVz5dXniG2zYJgnRVH4QFvSI',
    appId: '1:957697550017:android:37186ff56282825b879640',
    messagingSenderId: '957697550017',
    projectId: 'bowlingpro-2bc7a',
    storageBucket: 'bowlingpro-2bc7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbH6GAzgzwTQ39kakCSFi4r8HfN_hbIYs',
    appId: '1:957697550017:ios:a22d90e8a1b4025f879640',
    messagingSenderId: '957697550017',
    projectId: 'bowlingpro-2bc7a',
    storageBucket: 'bowlingpro-2bc7a.firebasestorage.app',
    iosBundleId: 'com.example.bowlingPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbH6GAzgzwTQ39kakCSFi4r8HfN_hbIYs',
    appId: '1:957697550017:ios:a22d90e8a1b4025f879640',
    messagingSenderId: '957697550017',
    projectId: 'bowlingpro-2bc7a',
    storageBucket: 'bowlingpro-2bc7a.firebasestorage.app',
    iosBundleId: 'com.example.bowlingPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7Q-hf9nMb9QkigrxXV62oX_I4LgXpHrE',
    appId: '1:957697550017:web:60dbaa878ba3950c879640',
    messagingSenderId: '957697550017',
    projectId: 'bowlingpro-2bc7a',
    authDomain: 'bowlingpro-2bc7a.firebaseapp.com',
    storageBucket: 'bowlingpro-2bc7a.firebasestorage.app',
    measurementId: 'G-KK9L612C7F',
  );
}
